#! /bin/sh -ex
# $Id$
# Copyright (C) 2004 Deneys S. Maartens <dsm@tlabs.ac.za>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#
#
# Use this script to generate the configure script used to configure and
# build this package.
#
# You need to have automake and autoconf installed.
# -or-
# You need to have automake, autoconf and libtool installed.

# find config directory
cfgaux=`dirname $0`
test $cfgaux = . && cfgaux=`pwd`
cfgaux=`basename $cfgaux`

aclocal -I $cfgaux
libtoolize --force # if we are making libs
autoheader
automake --add-missing
autoconf

# if config.status does not exist
if test ! -f config.status ; then
    # run configure, if it is executable
    if test -x configure ; then
        ./configure
    fi

# otherwise
else
    # run config.status, if it is executable
    if test -x config.status ; then
        ./config.status
    fi
fi

# -fin-
